server:
  port: 8040
spring:
  application:
    name: gateway
  zipkin:
    base-url: http://localhost:9411/
    discovery-client-enabled: false
    sleuth:
      sampler:
        #      抽样率不丢失任何数据达到100%
        #      建议默认0.1不会影响性能
        probability: 1.0

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


management:
  endpoints:
    web:
      exposure:
        include: 'gateway'
  endpoint:
    health:
      show-components: always
logging:
  level:
    reactor.netty: trace